tap:
  docker:
    registry: docker.io/kubeshark
    tag: latest
    imagepullpolicy: Always
    imagepullsecrets: []
  proxy:
    worker:
      srvport: 8897
    hub:
      port: 8898
      srvport: 8898
    front:
      port: 8899
      srvport: 8899
    host: 127.0.0.1
  regex: .*
  namespaces: []
  selfnamespace: kubeshark
  persistentstorage: false
  storagelimit: 200Mi
  storageclass: standard
  dryrun: false
  pcap: ""
  resources:
    worker:
      limits:
        cpu: 750m
        memory: 2Gi
      requests:
        cpu: 50m
        memory: 50Mi
    nginx:
      limits:
        cpu: 750m
        memory: 2Gi
      requests:
        cpu: 50m
        memory: 50Mi
    hub:
      limits:
        cpu: 750m
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 250Mi
  servicemesh: true
  tls: true
  packetcapture: libpcap
  ignoreTainted: false
  resourceLabels: {}
  nodeSelectorTerms: []
  ingress:
    enabled: true
    host: kubeshark.prod-us-east-1-eks-1.nonamesec.com
    tls: []
    auth:
      approvedDomains: [ nonamesecurity.com ]
    certManager: letsencrypt-prod
    alb:
      enabled: true
      public: true
      certificateArn: arn:aws:acm:us-east-1:758726565423:certificate/77d2e523-f94f-46bb-ac50-24e79db34005
      inboundCidr: 77.137.35.218/32, 0.0.0.0/0
  debug: false
logs:
  file: ""
kube:
  configpath: ""
  context: ""
dumplogs: false
headless: false
license: FT7YKAYBAEDUY2LDMVXHGZIB76DAAAIDAECEIYLUMEAQUAABAFJAD74IAAAQCUYB76EAAAAABL7YOBIBAL7YUAAAAD7APZH7QYA74B3XPMRGK3LBNFWCEORCEIWCEZLENF2GS33OEI5CEUCSJ4RCYITFNZSCEORRGY4DQNRUGUYTMMBZHE4SYITON5SGK4ZCHIYTAOBMEJQXA4C7MNWGSZLOORPWSZBCHIRDCMRYMF2GG33NMY4TO3RXOZUTQM3DM5VDE2DNOIYWIIRMEJ2XGZLSL5YG633ML5UWIIR2EJ2XGLLFMFZXILJSL4ZGYOKVIJCWCNDHEIWCE4TFMZZGK43IL52G623FNYRDUITFPFFGUZCINNUU62KKJNLDCULJJRBUU3DCNVGWST3JJJBE22SVGJJDATSOJFUXO2KZK54G4SLKN5UVK3COIJGFKOKCKJLEC2LGKEXFIMCJKIZUMZDQNB4US6KVHF4XIRKMIZXUSNTSNJ2U26LTGRQUOZCBJRZS2Q3TMI2EUV27OA4EW22DIVGVSUDCMVHTEWDHOUYVSTBVM5TW6S2JOFKHGSTNKNCGKUDKJ53XKWKLJBRUQ5LSGRSHIMTSNFUWOX3NKZJGOVLZN5ITKMDTIZ3HE33FKZ2EMZLZPFATOVSYO5XGQ22VKZ5DASCFPJMG4TKENBZG46DPKNITEWTFOFYGYV3OKJHUUMKHKNVHEZRQOY4F64BNJVGEWNLMPJJU2Z2HINDEMTLZNFPVMODBPBIE4YJTGI4WSU2PGBDFM3DVL5RGYUZTFVSXEWTVKQ4WM53ZPBJG26SROFZGURJXNRQTGZTUM5IEIUSBMZQTIVDNLBLUEWD2OBVXALKHHFGWM6LVGVKTSRLVK5JXUM3YL52FI23LLE2UIZLSIVDUS4TKKU2WWR3TJFVECSKQNJTUCVTVINQWSU3RNZVUCSJWII3W2OCBGRVF6ZDYLJQTI2SPIN3DGTLROEYXUY2OJVVWSVTENVEXGZZOLBVUI3TSMNZEOUSOJZLWU5TZKUXGOWCWGVRFUVKPGM4GWOBNKRFWCMRQGFCG2UC7HB4GOV2EIVDUWVCTOAZWI2TVLBWVQWLNIREG4SDBNVSG2S2DPFMVM5DMG42GOYTKJBGDMVTFJAYF6222JRCUO43IKV3TSVKJNZ4VQWS2OBWGQV3WJRRWQMRUNQZFOYSSG44W46SHMI4GS3TSM5YDONRZKVKFK23GIRHTSN2OPBRGSVTRJRKFKNJXNJYWIMRQJU2WKU2JGBJUMZSCINUDAMCJPFQWMQTQPF3WEOKMGVUEIYSKNAZG22LZLJQUY5KOGJDXORCMONNGERCIGBKEYQLZOV3EO6JWGNNHK6CPO4ZV6UCLPF2TIYLPKBVESWDWNRLVK2SFI5XXKQLHKRGDI5RYGFSFUSZWKNHUI6JNJ5IEC5THOJ2WOX3ENVEUSYTDMFMTC52WNZFWQR2XMZJEUSCZNA3GGRDZOJRDK6DRHFLTIU3XI5WXERLOKA3HGMT2G5GEYZLXFUYVAMKWKVVXUUSJKFSWQ3DTGFCGYN2INVGTMTBZJE3WQSTVOJVEC6KRORSUGMTNGVDGWMDZO5KGO6BYOJXGYWKRG5BDIZCPLJIFUZTZIMZXM2ZUJ5NFSTCYOJBEWRRWGZJDOT3RIEWWERRNGUZHQZCBOVNGW5SBOB4EQ4DGGJ5E66CTJJCVCLKLOM2XGWTIIUZHGRDJPFWEGZDRJFGEKLJZPA3EQM2PJRQW422NONMFK2CKINHGQNDSMI3C253IIRMDCZCKII2FSSKVOJVHUURSJBKVMR3FG5DHE4ZYHBKECSZXN5HVITDCKBDTEQ2TNF3XIN22NJETMWSYK5ZUCZKDMVUUEOC2NBUWCYZYHFQVK3C2MNMWEU2HKUZDI4TFG5MHCM3JMFSG6S3SFVSXM53ENFTFSN32LFKGMZ3QOR4FMRLTMNPTMZDVIJYUC5ZSIZKEOWTEJZLV622BGNHE6LKFJNMWK5LEPBAU4Z3IPIZHEWLBKVJWQ3JSMNZWSTCNGIZVSUBYPJYXS3RUGFYUKMKNGNJGURDTG4YECZ2BNRJHC6DCL5EEYNZSOQYFORJTMVCTGRLVIZVG2VSJNR5FAMDBLFLHE33WGBKFSS2CJNBXMTDQGMYXQTSOPBXVEZ3YJZXXKQJSJJAXOVSVNVNGENCBJ5JEEQKBOBUHSWSDPBUWC4BNIZMG44ZUNY3DKMSYLFVVM3DLJZMFARKRJRWS24LSNBDEWLJQHB3FIM2HJ43WIY2FL5TGKZTQGFPVS6DOPI2HCTJUMREFAVLPJU3TK53XKVSTS2BTGN3W23LHIRLWSLLFIF4XU6TTGRUDETTWMRSTS3BYJZZTGMTRN54DEVCVMFFUQZKBOFTXKS2JMJIEW2BYNFFUSLLWNJGTM42CNVAUC2CWPJXHGSKIK4YDQ3TVMYYTC2DUGFXW6Z2UM5MHI5DGM5ZFM3BWJQ3FKWLFMJGXMQKTONUTKZSTFVTVQ6SNMFIU66JTIQ4EGVKOINQVKWJWGZ5DK5KNKVRWQNCFINZDC2S2MVZVS3RYNVWGCMBTMVAXSNDLIFHUGUZWKM3HENKCGFUTAV2RG5WXS53UKFTTKZKDGRLWG3TNGM2EMLJVJNLEEQKNNFSHMZBVO5SGE2ZVGMWS22CEOZCTM5ZTFU4EGN2PNJAUI3C2MRGFS2RQPBHEQVDIMVEWIUDNIRJTGUTSHB4UMMDJIJ3XKVTZG5BFE4BTGNAWC5TGJRZVA52KJJVXKMTRLJIDATLIGBWW6MDMM5KGUQ3MJY4WWR3UJFIWK52NG5DHSYZRGRYEKWLHOM3U4UDNOU2DM23PGNLE6YZVGRIEMZLEGRGGY3DVPFITAYSDJBEXEZSTIF2TMZ2SJJDTCZKPHFVWKS27NFFW6MTSINTG2U32GFZFAZTOL5GU2SSNGJBVORLOKFWXATCWNZXGUR2RGFMHQURTPJXFE4LJNNUUMZ3HONHFAWCUINKESLKHMNUUOZS7GREUC53CJ44XASBUJZVDKZTRMN4FKQSWIZLUQZKUJ4YHM2RTMNHGKY2ZOR3WE32WNFCGSRKDOZLUM3KQPFNHMUTVFUYWO5LFKVBHUVKDOQXFOZRYGVFU2OLGNB4XQ33IKZMXGYLFOBWDS5ZCPUATCAUAEZX5W6373QE4KVEJEI2Z32TMJDZND2BRIH3BXWD4CECWODQ3NSPMCEIXOCPXPV7HP57P5HCFSCOACMICGOYMWJS4PBWZAXUBO463MYU6KCXSWVAMHYIUFQN4ZYA2GY2IHZE27MWGX7E5UZ7PGA57SX5PPWQOIAA=
scripting:
  env: {}
  source: ""
  watchScripts: true
