---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    kubeshark-created-by: kubeshark
    kubeshark-managed-by: kubeshark
  name: kubeshark-nginx
  namespace: '{{ .Values.tap.selfnamespace }}'
spec:
  ports:
    - name: kubeshark-nginx
      port: 80
      targetPort: 80
  selector:
    app: kubeshark-nginx
  type: NodePort
status:
  loadBalancer: {}
